        
    if Gui.Selection.isSelected(App.getDocument(ap).getObject("Rect")) == True:
        matExtrude()
		
		
def matExtrude():
	if App.ActiveDocument.Name == "Unnamed":
		ap=App.ActiveDocument.Name
		exec("""a=App.getDocument("{}").getObject("Extrude")""".format(ap),globals())
	elif App.ActiveDocument.Name == "Sans_nom":
		ap=App.ActiveDocument.Name
		exec("""a=App.getDocument("{}").getObject("Extrude")""".format(ap),globals())


	if a==None:
		pass
	elif Gui.Selection.isSelected(App.getDocument(ap).getObject("Extrude")) == True:

		Extrude="""_Material_Specifications_

Density:          """+FreeCAD.getDocument(ap).getObject("Extrude").Density+"""

COR:              """+FreeCAD.getDocument(ap).getObject("Extrude").COR+"""
STATICFRICTION:   """+FreeCAD.getDocument(ap).getObject("Extrude").Static_friction+"""
KINETICFRICTION:  """+FreeCAD.getDocument(ap).getObject("Extrude").Kinetic_friction+"""

_Numerical_Specifications_

_NormalParamaters_
CONTACT_TIME  """+FreeCAD.getDocument(ap).getObject("Extrude").Contact_time+"""

_TangentParamaters_
CONTACT_TIME  """+FreeCAD.getDocument(ap).getObject("Extrude").Contacttime+"""

_CohesionParamaters(Optional)_"""

		if os.path.isfile(FreeCAD.getDocument(ap).getObject("Extrude").Label+".MAT")==True:
			test=os.remove(FreeCAD.getDocument(ap).getObject("Extrude").Label+".MAT")

		WOBJ=open(FreeCAD.getDocument(ap).getObject("Extrude").Label+".txt", "w")
		WOBJ.write(Extrude)
		WOBJ.close()
		os.rename(dir_+"/"+FreeCAD.getDocument(ap).getObject("Extrude").Label+".txt",dir_+"/"+FreeCAD.getDocument(ap).getObject("Extrude").Label+".MAT")
	j=1
	for j in range (1,100):
		n=str(j)
		if j < 10 and App.getDocument(ap).getObject("Extrude00"+n)== None:
			pass
		elif j < 10 and Gui.Selection.isSelected(App.getDocument(ap).getObject("Extrude00"+n)) == True :
			Extrude="""_Material_Specifications_

Density:          """+FreeCAD.getDocument(ap).getObject("Extrude00"+n).Density+"""

COR:              """+FreeCAD.getDocument(ap).getObject("Extrude00"+n).COR+"""
STATICFRICTION:   """+FreeCAD.getDocument(ap).getObject("Extrude00"+n).Static_friction+"""
KINETICFRICTION:  """+FreeCAD.getDocument(ap).getObject("Extrude00"+n).Kinetic_friction+"""

_Numerical_Specifications_

_NormalParamaters_
CONTACT_TIME  """+FreeCAD.getDocument(ap).getObject("Extrude00"+n).Contact_time+"""

_TangentParamaters_
CONTACT_TIME  """+FreeCAD.getDocument(ap).getObject("Extrude00"+n).Contacttime+"""

_CohesionParamaters(Optional)_"""

			if os.path.isfile(FreeCAD.getDocument(ap).getObject("Extrude00"+n).Label+".MAT")==True:
				test=os.remove(FreeCAD.getDocument(ap).getObject("Extrude00"+n).Label+".MAT")

			WOBJ=open(FreeCAD.getDocument(ap).getObject("Extrude00"+n).Label+".txt", "w")
			WOBJ.write(Extrude)
			WOBJ.close()
			os.rename(dir_+"/"+FreeCAD.getDocument(ap).getObject("Extrude00"+n).Label+".txt",dir_+"/"+FreeCAD.getDocument(ap).getObject("Extrude00"+n).Label+".MAT")

		if j > 10 and App.getDocument(ap).getObject("Extrude0"+n)== None:
			pass
		elif j>10 and Gui.Selection.isSelected(App.getDocument(ap).getObject("Extrude0"+n)) == True :

			Extrude="""_Material_Specifications_

Density:          """+FreeCAD.getDocument(ap).getObject("Extrude0"+n).Density+"""

COR:              """+FreeCAD.getDocument(ap).getObject("Extrude0"+n).COR+"""
STATICFRICTION:   """+FreeCAD.getDocument(ap).getObject("Extrude0"+n).Static_friction+"""
KINETICFRICTION:  """+FreeCAD.getDocument(ap).getObject("Extrude0"+n).Kinetic_friction+"""

_Numerical_Specifications_

_NormalParamaters_
CONTACT_TIME  """+FreeCAD.getDocument(ap).getObject("Extrude0"+n).Contact_time+"""

_TangentParamaters_
CONTACT_TIME  """+FreeCAD.getDocument(ap).getObject("Extrude0"+n).Contacttime+"""

_CohesionParamaters(Optional)_"""

			if os.path.isfile(FreeCAD.getDocument(ap).getObject("Extrude0"+n).Label+".MAT")==True:
				test=os.remove(FreeCAD.getDocument(ap).getObject("Extrude0"+n).Label+".MAT")

			WOBJ=open(FreeCAD.getDocument(ap).getObject("Extrude0"+n).Label+".txt", "w")
			WOBJ.write(Extrude)
			WOBJ.close()
			os.rename(dir_+"/"+FreeCAD.getDocument(ap).getObject("Extrude0"+n).Label+".txt",dir_+"/"+FreeCAD.getDocument(ap).getObject("Extrude0"+n).Label+".MAT")